//
// MapsforgeKit — Native Mapsforge implementation for Apple platforms
// Copyright (C) 2026 MapsforgeKit contributors
//
// LGPL-3.0; see LICENSE.
//
// Swift port of `MapHeaderSnapshotTest.java`. Reads the full header of
// `bremen.map` via `MapFile`, dumps every field to
// `build/fixtures/bremen-header.txt` for inspection and asserts the dump
// against the committed snapshot at `resources/expected-bremen-header.txt`.
//

import Foundation
import Testing
@testable import MapsforgeCore

@Suite("Map header snapshot")
struct MapHeaderSnapshotTests {

    /// Locale Mapsforge's Java reference uses (`%.6f` → `52,910340`).
    let germanLocale = Locale(identifier: "de_DE")

    /// Default time zone of the machine that produced the committed snapshot.
    let snapshotTimeZone = TimeZone(identifier: "Europe/Berlin")!

    @Test("Reads bremen.map header and matches the committed full-header snapshot")
    func readsAndSnapshotsBremenMapHeader() throws {
        let resources = try Self.locateResourcesDirectory()
        let mapURL = resources.appendingPathComponent("bremen.map")
        let snapshotURL = resources.appendingPathComponent("expected-bremen-header.txt")

        let mapFile = try MapFile(url: mapURL)
        let info = mapFile.mapFileInfo

        let fullDump = formatFullHeader(info)

        // Always write the live dump for inspection — even when the test passes.
        let fixturePath = try Self.writeFullDump(fullDump)
        print("Wrote full header dump: \(fixturePath.path)")

        // Compare against the committed reference snapshot.
        guard FileManager.default.fileExists(atPath: snapshotURL.path) else {
            try fullDump.write(to: snapshotURL, atomically: true, encoding: .utf8)
            Issue.record("""
                No header snapshot existed yet — wrote one to:
                \(snapshotURL.path)
                Review it and commit it. Re-run the test; it should pass.
                """)
            return
        }

        let expected = try String(contentsOf: snapshotURL, encoding: .utf8)
        if expected != fullDump {
            Issue.record("""
                bremen.map full header dump differs from snapshot.

                Snapshot: \(snapshotURL.path)
                Live dump: \(fixturePath.path)

                Diff (- expected / + actual):
                \(Self.simpleDiff(expected: expected, actual: fullDump))
                """)
        }
    }

    // MARK: - Formatting (matches MapHeaderSnapshotTest.java line for line)

    private func formatFullHeader(_ info: MapFileInfo) -> String {
        var sb = ""
        sb += "# Full Mapsforge header dump for bremen.map\n"
        sb += "# Generated by MapHeaderSnapshotTest. Not normative — see\n"
        sb += "# expected/bremen-header.txt for the structural snapshot.\n"
        sb += "\n"

        sb += "File format\n"
        sb += field("fileVersion",     "\(info.fileVersion)")
        sb += field("fileSize",        "\(info.fileSize)")
        sb += field("projectionName",  info.projectionName)
        sb += field("tilePixelSize",   "\(info.tilePixelSize)")
        sb += "\n"

        sb += "Build metadata\n"
        sb += field("mapDate",   "\(info.mapDate)  (\(formatJavaDate(milliseconds: info.mapDate)))")
        sb += field("createdBy", info.createdBy ?? "null")
        sb += field("comment",   info.comment ?? "null")
        sb += "\n"

        sb += "Geographic coverage\n"
        sb += field("boundingBox",    formatBBox(info.boundingBox))
        sb += field("startPosition",  formatLatLong(info.startPosition))
        sb += field("startZoomLevel", info.startZoomLevel.map { "\($0)" } ?? "null")
        sb += "\n"

        sb += "Zoom levels\n"
        sb += field("zoomLevelMin", "\(info.zoomLevelMin)")
        sb += field("zoomLevelMax", "\(info.zoomLevelMax)")
        sb += "\n"

        sb += "Languages and POI/Way tags\n"
        sb += field("languagesPreference", info.languagesPreference ?? "null")
        sb += field("numberOfPoiTags",     "\(info.poiTags.count)")
        sb += field("numberOfWayTags",     "\(info.wayTags.count)")
        sb += "\n"

        sb += "POI tags (first 300)\n"
        sb += formatTagSample(info.poiTags, max: 300)
        sb += "\n"

        sb += "Way tags (first 300)\n"
        sb += formatTagSample(info.wayTags, max: 300)
        return sb
    }

    private func field(_ name: String, _ value: String) -> String {
        let padded = name.padding(toLength: 25, withPad: " ", startingAt: 0)
        return "  \(padded)= \(value)\n"
    }

    private func formatBBox(_ bbox: BoundingBox) -> String {
        String(
            format: "minLat=%.6f minLon=%.6f maxLat=%.6f maxLon=%.6f",
            locale: germanLocale,
            bbox.minLatitude, bbox.minLongitude, bbox.maxLatitude, bbox.maxLongitude
        )
    }

    private func formatLatLong(_ p: LatLong?) -> String {
        guard let p else { return "null" }
        return String(format: "lat=%.6f lon=%.6f", locale: germanLocale, p.latitude, p.longitude)
    }

    private func formatTagSample(_ tags: [MapsforgeCore.Tag], max: Int) -> String {
        guard !tags.isEmpty else { return "  (none)\n" }
        let limit = Swift.min(tags.count, max)
        var out = ""
        for i in 0..<limit {
            let idx = String(format: "%3d", i)
            out += "  [\(idx)] \(tags[i])\n"
        }
        if tags.count > limit {
            out += "  ... (\(tags.count - limit) more)\n"
        }
        return out
    }

    /// Reproduces Java's `Date.toString()` format
    /// (`"EEE MMM dd HH:mm:ss zzz yyyy"`, en_US, system TZ at snapshot time).
    ///
    /// Apple's `DateFormatter` localises zone abbreviations (`MEZ` vs. `CET`)
    /// even with `en_US_POSIX`, so we substitute the abbreviation Java would
    /// emit (`CET` / `CEST`) explicitly.
    private func formatJavaDate(milliseconds: Int64) -> String {
        let date = Date(timeIntervalSince1970: TimeInterval(milliseconds) / 1000.0)
        let df = DateFormatter()
        df.locale = Locale(identifier: "en_US_POSIX")
        df.timeZone = snapshotTimeZone
        df.dateFormat = "EEE MMM dd HH:mm:ss"
        let prefix = df.string(from: date)
        df.dateFormat = "yyyy"
        let year = df.string(from: date)
        let abbr = snapshotTimeZone.isDaylightSavingTime(for: date) ? "CEST" : "CET"
        return "\(prefix) \(abbr) \(year)"
    }

    // MARK: - File system helpers

    private static func locateResourcesDirectory() throws -> URL {
        let here = URL(fileURLWithPath: #filePath)
        var dir = here.deletingLastPathComponent()
        let fm = FileManager.default
        for _ in 0..<10 {
            let candidate = dir
                .appendingPathComponent("resources", isDirectory: true)
                .appendingPathComponent("bremen.map")
            if fm.fileExists(atPath: candidate.path) {
                return dir.appendingPathComponent("resources", isDirectory: true)
            }
            let parent = dir.deletingLastPathComponent()
            if parent.path == dir.path { break }
            dir = parent
        }
        throw NSError(
            domain: "MapsforgeCoreTests",
            code: 1,
            userInfo: [NSLocalizedDescriptionKey:
                "Could not locate `resources/bremen.map` walking up from \(here.path)"]
        )
    }

    private static func writeFullDump(_ content: String) throws -> URL {
        let here = URL(fileURLWithPath: #filePath)
        // apple/MapsforgeKit/Tests/MapsforgeCoreTests/<file> → apple/MapsforgeKit
        let packageDir = here
            .deletingLastPathComponent()
            .deletingLastPathComponent()
            .deletingLastPathComponent()
        let fixturesDir = packageDir
            .appendingPathComponent("build", isDirectory: true)
            .appendingPathComponent("fixtures", isDirectory: true)
        try FileManager.default.createDirectory(
            at: fixturesDir, withIntermediateDirectories: true
        )
        let url = fixturesDir.appendingPathComponent("bremen-header.txt")
        try content.write(to: url, atomically: true, encoding: .utf8)
        return url
    }

    private static func simpleDiff(expected: String, actual: String) -> String {
        let e = expected.split(separator: "\n", omittingEmptySubsequences: false)
        let a = actual.split(separator: "\n", omittingEmptySubsequences: false)
        let max = Swift.max(e.count, a.count)
        var out = ""
        for i in 0..<max {
            let el: Substring? = i < e.count ? e[i] : nil
            let al: Substring? = i < a.count ? a[i] : nil
            if el == nil {
                out += "+ \(al!)\n"
            } else if al == nil {
                out += "- \(el!)\n"
            } else if el != al {
                out += "- \(el!)\n"
                out += "+ \(al!)\n"
            }
        }
        return out
    }
}
